swipe:
  3:
  4:
    left:
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT:
          window: 'next' # Move window to next workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Left' # Move window to left side
    right:
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT:
          window: 'prev' # Move window to previous workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Right'  # Move window to right side
    up:
      command: 'xdotool key ctrl+F9'
      LEFTSHIFT:
        command: 'xdotool key --clearmodifiers ctrl+F10'
      LEFTMETA:
        command: 'xdotool key --clearmodifiers super+ctrl+Up'  # Move window to up side
    down:
      window:
          maximized: 'toggle'    # Toggle Maximize/Unmaximize Window
      LEFTMETA:
        command: 'xdotool key --clearmodifiers super+ctrl+Down'  # Move window to down side

pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
    out:
      command: 'xdotool key ctrl+minus'
  4:
    in:
      command: 'xdotool key ctrl+F9'
      LEFTSHIFT:
        command: 'xdotool key --clearmodifiers ctrl+F10'

# threshold:
#   swipe: 0.3
#   pinch: 0.1
#
# interval:
#   swipe: 1
#   pinch: 1

plugin:
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option
